### ISSUE TITLE
Deploy app in App Store

### ISSUE THREAD

**Issue by fredfalcon** [OWASP/BLT-Flutter#237]
@hblankenship can you please help us with this?

the identifier is com.apps.blt and app name: OWASP BLT

**Comment by hblankenship** [comment]
I will send you and email regarding the program.

**Comment by DonnieBLT** [comment]
@hblankenship can you please setup an API key that we can use to integrate into Codemagic? https://docs.codemagic.io/flutter-code-signing/ios-code-signing/#step-1-creating-an-app-store-api-key-for-codemagic

**Comment by hblankenship** [comment]
Done.

**Comment by DonnieBLT** [comment]
https://apps.apple.com/us/app/owasp-blt/id6448071954
