### ISSUE TITLE
Task: UI Fix on Monthly Leaderboard

### ISSUE THREAD

**Issue by solo-daemon** [OWASP/BLT-Flutter#287]

**Comment by solo-daemon** [comment]
1)  There should be text dispalyed when there is no data to be displayed
2)  The month button should be center aligned
3) The bottom sheet can have all months in the future months can be deactivated

https://user-images.githubusercontent.com/65587505/230470697-2dbefe71-77f9-4142-b98c-136670323848.mp4

**Comment by letsintegreat** [comment]
> 3. The bottom sheet can have all months in the future months can be deactivated

Why flood the user with options that are not relevant? I think showing only the months that are available is better, as user will only have to navigate through the available options and quickly choose the required one, thus a better a UX. What do you think, @just-ary27 @fredfalcon?

**Comment by zaeemkhan1999** [comment]
please assign me this
