### ISSUE TITLE
Show plain text in issue card instead of markdown syntax

### ISSUE THREAD

**Issue by solo-daemon** [OWASP/BLT-Flutter#289]

**Comment by AtmegaBuzz** [comment]
In the backend we've moved the description from plain text to markdown, so the user can just write the markdown but in the mobile this markdown text is shown just as it is, it should be rendered. For eg Readme.md file we write it in markdown but while viewing it is rendered to beautiful layout. Add this feature of rendering markdown in mobile app.

**Comment by letsintegreat** [comment]
Markdown feature is implemented in issues page. But there's a list of issues card in the home page, that needs fixing. It shows markdown text as plain text. Either render the markdown, if that looks weird, show plain text without formatters.

**Comment by letsintegreat** [comment]
@DonnieBLT This issue can be closed as it is redundant after the introduction of the "title" field in issue model.

**Comment by Uttkarsh-raj** [comment]
> @DonnieBLT This issue can be closed as it is redundant after the introduction of the "title" field in issue model.

@DonnieBLT i have tested and made the changes if necessary in the pr i have made...
Link: https://github.com/OWASP/BLT-Flutter/pull/337
