### ISSUE TITLE
Task: Update Usage of barrel Imports

### ISSUE THREAD

**Issue by shatanikmahanty** [OWASP/BLT-Flutter#302]
Currently project uses normal imports.

May we use barrel imports like a single file for each folders where files in it are exported? It will result in cleaner imports and reduce clutter in files with large number of imports.

**Comment by DonnieBLT** [comment]
https://marvinh.dev/blog/speeding-up-javascript-ecosystem-part-7/

**Comment by shatanikmahanty** [comment]
Hi @DonnieBLT thanks for that insightful article that helped me learn new things. But I believe Dart is very differently architectured than JS and dart removes unnecessary imports caused by barrel files.

If you look at the flutter provided material library it also uses barrel imports.

**Comment by DonnieBLT** [comment]
Thank you! So the performance would be the same?

**Comment by shatanikmahanty** [comment]
> Thank you! So the performance would be the same?

Yes

**Comment by jassirr** [comment]
@DonnieBLT can i take up this issue!
