### ISSUE TITLE
Screenshots for app store

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT-Flutter#304]
would someone be interested in creating screenshots for the app store?

You must upload a screenshot for 12.9-inch iPad Pro (2nd generation) displays.
You must upload a screenshot for 12.9-inch iPad Pro (6th generation) displays.
You must upload a screenshot for 5.5-inch iPhone displays.
You must upload a screenshot for 6.5-inch iPhone displays.

**Comment by AtmegaBuzz** [comment]
I am intreasted, Should i run the app in different emulator of these sizes and take the ss ?

**Comment by DonnieBLT** [comment]
Yes from the simulator is good.  They must match the height and width requirements exactly so please check those. 3 screenshots for each model is sufficient. Thank you!

**Comment by AtmegaBuzz** [comment]
Ok got it Thanks @letsintegreat @DonnieBLT

**Comment by AtmegaBuzz** [comment]
https://drive.google.com/drive/folders/1ta8Fc5t2orGxC_qyf_CMBeRcZASR6rnP?usp=sharing 
Screenshots are uploaded here
