### ISSUE TITLE
Project: Flutter > Dark Mode Theme

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT-Flutter#344]
Add designs for a dark theme in the Figma file, then implement a generic theme manager for future themes.

**Comment by Dante291** [comment]
@DonnieBLT Could you please share the link of the Figma file where I can add designs for dark theme, and when get approved by you I will start working on it

**Comment by DonnieBLT** [comment]
Check the readme. Let me know if not

**Comment by Dante291** [comment]
@DonnieBLT First I will propose my designs for this issue and after getting them approved then I will assign myself to work on this, this way I will be able to work on other issues while making designs for dark theme.

**Comment by Dante291** [comment]
> Check the readme. Let me know if not

Found it, Thanks

**Comment by Dante291** [comment]
@DonnieBLT @just-ary27 I have added dark theme designs please check out [here](https://www.figma.com/file/uCd2HxU2Hvbcl01Gv2vUU1/Bug-Logging-Tool-(with-dark-theme)?type=design&node-id=0-1&mode=design&t=UaC1UGsJYMuXnpyr-0) and tell any modifications I need to do in this and if its ok I can proceed implementing the feature into the App
