### ISSUE TITLE
fix flutter issues 

### ISSUE THREAD

**Issue by DonnieBLT** [OWASP/BLT-Flutter#351]
info • 'WillPopScope' is deprecated and shouldn't be used. Use PopScope instead. This feature was deprecated after v3.12.0-1.0.pre • lib/src/pages/home/home.dart:214:12 • deprecated_member_use
   info • 'WillPopScope.new' is deprecated and shouldn't be used. Use PopScope instead. This feature was deprecated after v3.12.0-1.0.pre • lib/src/pages/home/home.dart:214:12 • deprecated_member_use
   info • 'WillPopScope' is deprecated and shouldn't be used. Use PopScope instead. This feature was deprecated after v3.12.0-1.0.pre • lib/src/pages/leaderboards/monthly_leaderboard.dart:78:12 • deprecated_member_use
   info • 'WillPopScope.new' is deprecated and shouldn't be used. Use PopScope instead. This feature was deprecated after v3.12.0-1.0.pre • lib/src/pages/leaderboards/monthly_leaderboard.dart:78:12 • deprecated_member_use

**Comment by Uttkarsh-raj** [comment]
Hii @DonnieBLT ill look into this issue.
/assign

**Comment by DonnieBLT** [comment]
Thanks!

**Comment by Dante291** [comment]
@Uttkarsh-raj Sorry I actually forgot to assign myself and start working on it because it was a quick fix and raised a PR too

**Comment by Uttkarsh-raj** [comment]
@Dante291 oh ok ...
